#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : libvisio
Version  : 0.1.7
Release  : 12
URL      : https://dev-www.libreoffice.org/src/libvisio-0.1.7.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libvisio-0.1.7.tar.xz
Summary  : Library for parsing the visio file format structure
Group    : Development/Tools
License  : MPL-2.0-no-copyleft-exception
Requires: libvisio-bin = %{version}-%{release}
Requires: libvisio-lib = %{version}-%{release}
Requires: libvisio-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : gperf
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : sed
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libvisio is a library and a set of tools for reading and converting MS
Visio diagrams.

%package bin
Summary: bin components for the libvisio package.
Group: Binaries
Requires: libvisio-license = %{version}-%{release}

%description bin
bin components for the libvisio package.


%package dev
Summary: dev components for the libvisio package.
Group: Development
Requires: libvisio-lib = %{version}-%{release}
Requires: libvisio-bin = %{version}-%{release}
Provides: libvisio-devel = %{version}-%{release}
Requires: libvisio = %{version}-%{release}

%description dev
dev components for the libvisio package.


%package doc
Summary: doc components for the libvisio package.
Group: Documentation

%description doc
doc components for the libvisio package.


%package lib
Summary: lib components for the libvisio package.
Group: Libraries
Requires: libvisio-license = %{version}-%{release}

%description lib
lib components for the libvisio package.


%package license
Summary: license components for the libvisio package.
Group: Default

%description license
license components for the libvisio package.


%prep
%setup -q -n libvisio-0.1.7
cd %{_builddir}/libvisio-0.1.7
pushd ..
cp -a libvisio-0.1.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685634466
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1685634466
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libvisio
cp %{_builddir}/libvisio-%{version}/COPYING.MPL %{buildroot}/usr/share/package-licenses/libvisio/9744cedce099f727b327cd9913a1fdc58a7f5599 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/vsd2raw
/V3/usr/bin/vsd2text
/V3/usr/bin/vsd2xhtml
/V3/usr/bin/vss2raw
/V3/usr/bin/vss2text
/V3/usr/bin/vss2xhtml
/usr/bin/vsd2raw
/usr/bin/vsd2text
/usr/bin/vsd2xhtml
/usr/bin/vss2raw
/usr/bin/vss2text
/usr/bin/vss2xhtml

%files dev
%defattr(-,root,root,-)
/usr/include/libvisio-0.1/libvisio/VisioDocument.h
/usr/include/libvisio-0.1/libvisio/libvisio.h
/usr/lib64/libvisio-0.1.so
/usr/lib64/pkgconfig/libvisio-0.1.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libvisio/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libvisio-0.1.so.1.0.7
/usr/lib64/libvisio-0.1.so.1
/usr/lib64/libvisio-0.1.so.1.0.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libvisio/9744cedce099f727b327cd9913a1fdc58a7f5599
